version: '3'

services:
  eclipse-mosquitto:
    image: eclipse-mosquitto
    container_name: eclipse-mosquitto
    tty: true
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
      - 8883:8883
    command: mosquitto
    networks:
      - mosquitto-net

networks:
  mosquitto-net:
    driver: bridge
